# cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Uploading to GCS..."
      gsutil -m cp -r * gs://news_assistant_main/
options:
  logging: CLOUD_LOGGING_ONLY
